### ISSUE TITLE
Django 1.8: relation "auth_user" does not exist

### ISSUE THREAD

**Issue by Heleen** [evonove/django-stored-messages#18]
Using `django-stored-messages` in my project causes the `relation "auth_user" does not exist` error after upgrading to django 1.8 (specifically when running tests where it builds a new database from scratch).
Adding explicit migrations for `django-stored-messages` solves the problem (like suggested in https://github.com/evonove/django-oauth-toolkit/issues/204#issuecomment-77984967), but maybe migrations could be added to the project itself?

Note: you will have to use the `--fake-initial` flag with `migrate` in django 1.8. See the [django docs](https://docs.djangoproject.com/en/1.8/topics/migrations/#adding-migrations-to-apps) for more information.

**Comment by nthall** [comment]
Forgive me if I'm mistaken, but it looks like the main reason this failed on Travis is that django-rest-framework dropped support for django <1.7 -- seems like a pretty reasonable decision on their part, any chance this project could do the same? I suppose the alternative would be to specify DRF versions carefully in tox, but I'm not experienced with tox so I've no idea if that's possible; at any rate it seems to me like overkill to go to much effort at all to support django as old as 1.4.
